name          'BillWeiss-zsh'
version       '0.0.1'
source        'https://github.com/BillWeiss/puppet-zsh'
author        'BillWeiss'
license       'Apache License, Version 2.0'
summary       'Simple zsh module'
description   'Just a module to install zsh'
project_page  'https://github.com/BillWeiss/puppet-zsh'

dependency 'puppetlabs/stdlib'
